version: '3.5' 

services:

  ex303:
    image: jonikiviluoto/jeejee
    build: .
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - USERNAME
      - PASSWORD
      - REPONAME
