version: '3.5' 

services:

  backend:
    image: jonikiviluoto/backend
    build: ./ml-kurkkumopo-backend
    ports:
            - 5000:5000
    volumes:
            - model:/src/model

  frontend:
    image: jonikiviluoto/frontend
    build: ./ml-kurkkumopo-frontend
    ports:
            - 3000:3000

  training:
          image: jonikiviluoto/training
          build: ./ml-kurkkumopo-training
          volumes:
                  - imgs:/src/imgs
                  - model:/src/model

volumes:
        imgs: 
        model:

