version: '3.5'  

services: 
    back:
      image: jonikiviluoto/ex205back
      ports:
              - 8000:8000
      build: ./back
      environment:
              -  REDIS=redis

    frontend:
      image: jonikiviluoto/front
      build: ./front
      ports:
              - 5000:5000

    redis:
      image: redis


      #front: 
      # image: jonikiviluoto/ex205front
      # ports: 
      #  - 5000:5000 
      # build: ./front
